# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4428d92e8603a49ac3dd6c0fb3b0ba9787e2ce4565cf72200ab52d6ad7825d54430034ebf1b0ea77008838cddea269c6b4fe7316c75bb61062bde5dd1bc07bc1

test:
  secret_key_base: 119c503c189b37589b0c9e8dd213707d2e824d3dc03b57537ddd56b2153d5b0cea9870c6201c17053083b1eb7ec1b9cdde8f5f653c35e653609eee0f5898515e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
